# Generated by Django 5.2.17 on 2026-10-01 03:15

import core_api.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'audit event',
                'db_table': 'audit_event',
            },
        ),
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('to', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('html', models.TextField(blank=True, default='')),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('user_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'outgoing email',
                'verbose_name_plural': 'outgoing emails',
                'db_table': 'outgoing_email',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField(null=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_setting',
            },
        ),
    ]
