# Generated by Django 5.2.17 on 2026-10-01 04:17

import core_api.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('channel', models.CharField(max_length=32)),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('user_id', models.CharField(blank=True, default='', max_length=64)),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'delivery_attempt',
            },
        ),
        migrations.CreateModel(
            name='JobHeartbeat',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_run_at', models.DateTimeField()),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'job_heartbeat',
            },
        ),
    ]
