# Generated by Django 5.2.17 on 2026-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_system', '0002_admin_ops'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('last_web_at', models.DateTimeField(blank=True, null=True)),
                ('last_agent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_presence',
            },
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('key', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_stat',
                'indexes': [models.Index(fields=['date'], name='daily_stat_date_6e0cd1_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'date'), name='daily_stat_unique')],
            },
        ),
        migrations.CreateModel(
            name='EventCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('total_ms', models.FloatField(default=0)),
                ('hist', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'event_count',
                'indexes': [models.Index(fields=['kind', 'date'], name='event_count_kind_158f05_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'kind', 'key'), name='event_count_unique')],
            },
        ),
        migrations.CreateModel(
            name='UserDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('date', models.DateField(db_index=True)),
                ('web', models.BooleanField(default=False)),
                ('agent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_day',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'date'), name='user_day_unique')],
            },
        ),
    ]
