# Generated by Django 5.2.17 on 2026-10-10 14:44

import core_api.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_system', '0003_insights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('reason', models.CharField(choices=[('bounce', 'Hard bounce'), ('complaint', 'Complaint'), ('manual', 'Added by an admin')], default='manual', max_length=16)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'suppressed address',
                'verbose_name_plural': 'suppressed addresses',
                'db_table': 'email_suppression',
            },
        ),
        migrations.AddField(
            model_name='outgoingemail',
            name='category',
            field=models.CharField(blank=True, db_default='', default='', max_length=32),
        ),
        migrations.AddField(
            model_name='outgoingemail',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingemail',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], db_index=True, default='queued', max_length=16),
        ),
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('enabled', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_preference',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'category'), name='email_preference_unique')],
            },
        ),
    ]
