# Generated by Django 5.2.17 on 2026-10-10 14:44

import core_api.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_system', '0004_email_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('journey', models.CharField(max_length=64)),
                ('key', models.CharField(blank=True, default='', max_length=128)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('done', 'Done'), ('exited', 'Exited')], default='active', max_length=8)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('next_at', models.DateTimeField(blank=True, null=True)),
                ('holdout', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'lifecycle_enrollment',
                'indexes': [models.Index(fields=['status', 'next_at'], name='lifecycle_e_status_53252b_idx'), models.Index(fields=['journey', 'entered_at'], name='lifecycle_e_journey_48d4dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'journey', 'key'), name='lifecycle_enrollment_unique')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'lifecycle_signal',
                'indexes': [models.Index(fields=['user_id', 'name', 'at'], name='lifecycle_s_user_id_5088ac_idx'), models.Index(fields=['at'], name='lifecycle_s_at_958265_idx')],
            },
        ),
        migrations.CreateModel(
            name='LifecycleSend',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('journey', models.CharField(max_length=64)),
                ('step', models.CharField(max_length=64)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('holdout', models.BooleanField(default=False)),
                ('target', models.CharField(blank=True, default='', max_length=64)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_system.outgoingemail')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='platform_lifecycle.enrollment')),
            ],
            options={
                'verbose_name': 'lifecycle email',
                'verbose_name_plural': 'lifecycle emails',
                'db_table': 'lifecycle_send',
                'indexes': [models.Index(fields=['journey', 'step', 'sent_at'], name='lifecycle_s_journey_5a8daf_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'step'), name='lifecycle_send_unique')],
            },
        ),
    ]
